trigger: none
pr: none

parameters:
  - name: version
    type: string
    default: patch
    values:
      - patch
      - minor
      - major
  - name: dryRun
    type: boolean
    default: false
  - name: publishPublic
    type: boolean
    default: true
  - name: publishInternal
    type: boolean
    default: true

variables:
  - group: studadm-general-params

resources:
  repositories:
    - repository: stratus-templates
      type: git
      name: Cloud Excellence Team/stratus-templates
      ref: main

pool:
  vmImage: 'ubuntu-latest'

extends:
  template: templates/security/security-scans.yml@stratus-templates
  parameters:
    break: false
    steps:
      - template: /templates/npm/publish.yml@stratus-templates
        parameters:
          version: ${{ parameters.version }}
          nodeVersion: 18.x
          verbose: false
          dryRun: ${{ parameters.dryRun }}
          publishPublic: ${{ parameters.publishPublic }}
          publishInternal: ${{ parameters.publishInternal }}
